# Generated by Django 5.0.3 on 2024-03-14 17:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Party',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('initials', models.CharField(max_length=10)),
                ('icon', models.ImageField(blank=True, null=True, upload_to='product_images/%Y/%m/')),
                ('votes', models.IntegerField(default=0)),
            ],
            options={
                'verbose_name_plural': 'Parties',
            },
        ),
    ]
