# Generated by Django 5.0.3 on 2024-03-14 18:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('poll', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=255)),
                ('id_number', models.CharField(max_length=9)),
                ('date_of_birth', models.DateField()),
                ('region', models.CharField(choices=[('AV', 'Aveiro'), ('BE', 'Beja'), ('BG', 'Braga'), ('BN', 'Bragança'), ('CB', 'Castelo Branco'), ('CO', 'Coimbra'), ('EV', 'Évora'), ('FA', 'Faro'), ('GU', 'Guarda'), ('LE', 'Leiria'), ('LX', 'Lisboa'), ('PG', 'Portalegre'), ('PO', 'Porto'), ('SA', 'Santarém'), ('SE', 'Setúbal'), ('VC', 'Viana do Castelo'), ('VR', 'Vila Real'), ('VS', 'Viseu'), ('AC', 'Açores'), ('MA', 'Madeira'), ('EU', 'Outros países da Europa'), ('FE', 'Outros países fora da Europa')], max_length=2)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
