# Generated by Django 5.0.3 on 2024-03-22 15:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('poll', '0002_profile'),
    ]

    operations = [
        migrations.CreateModel(
            name='Vote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('party', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='poll.party')),
                ('voter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='poll.profile')),
            ],
        ),
    ]
